Repository flipkart-incubator/nexus, pull requests merged in 2021-07, with the labels that each got.

#13 User configureable `nexus-cluster-name`
  internal/raft/node.go
  pkg/raft/opts.go
Labels: bug fix, ready for review

#18 Support for streaming snapshots
  examples/mysql_repl/store/db.go
  examples/redis_repl/store/db.go
  examples/redis_repl/store/db_test.go
  go.mod
  go.sum
  internal/models/internal.proto
  internal/raft/node.go
  internal/raft/replicator.go
  internal/raft/replicator_test.go
  internal/raft/snap/snapshotter.go
  internal/raft/snap/snapshotter_test.go
  pkg/db/storage.go
Labels: ready for review

#20 `ListMembers` should return accurate node status
  examples/repl/main.go
  internal/grpc/client.go
  internal/grpc/service_test.go
  internal/models/internal.pb.go
  internal/models/internal.proto
  internal/raft/replicator.go
  internal/raft/replicator_test.go
  models/internal.pb.go
  models/internal.proto
  pkg/api/nexus.go
  pkg/api/nexus.pb.go
  pkg/api/nexus.proto
  pkg/api/nexus_grpc.pb.go
Labels: enhancement, ready for review
